name: ui-jobmetrics
rundeckPluginVersion: 1.2
author: PagerDuty
date: 2024-01-29
version: 1.2.0
providers:
    - name: ui-jobmetrics
      service: UI
      plugin-type: ui
      title: 'Job Execution Metrics'
      description: 'Job Execution Summary Views on Job List and Job Activities pages'
      ui:
        - pages: ['menu/jobs', 'scheduledExecution/show']
          scripts:
            - js/chart.min.js
            - js/init.js
            - js/jobmetrics.js
          styles:
            - css/styles.css