name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.9.4
      
      - name: Verify Directory Structure
        run: |
          mkdir -p src/main/rdplugin/assets/js/lib
          mkdir -p src/main/rdplugin/assets/scss
          cp -r src/main/rdplugin/resources/js/* src/main/rdplugin/assets/js/
          ls -la src/main/rdplugin/assets/js
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Clean
        run: ./gradlew clean --no-daemon
      
      - name: Asset Compile
        run: |
          export GRADLE_OPTS="-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError"
          ./gradlew assetCompile --no-daemon --info \
            -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError"
      
      - name: Build Plugin
        run: |
          export GRADLE_OPTS="-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError"
          ./gradlew build --no-daemon --info \
            -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError"
      
      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui-job-metrics
          path: build/distributions/*.zip
          if-no-files-found: error